### ISSUE TITLE
[Chicken] Can't write parquet file when joining large dataframe

### ISSUE THREAD

**Issue by anhnongdan** [anhnongdan/Spark1.6_Problems#1]
ON VT cluster.
A table with 26863 records.

=> 1 node on cluster is timeout. 

This problem is recurring, no matter if the kernel is restarted, or code re-executed.

**Comment by anhnongdan** [comment]
Driver shows SparkContext shutdown error:

```
Py4JJavaError: An error occurred while calling o292.parquet.
: org.apache.spark.SparkException: Job aborted.
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1.apply$mcV$sp(InsertIntoHadoopFsRelation.scala:156)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1.apply(InsertIntoHadoopFsRelation.scala:108)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1.apply(InsertIntoHadoopFsRelation.scala:108)

Caused by: org.apache.spark.SparkException: Job 33 cancelled because SparkContext was shut down
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:806)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:804)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
```

```
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 23.2 failed 4 times, most recent failure: Lost task 1.3 in stage 23.2 (TID 4382, ip-10-58-16-5.dn.pc): ExecutorLostFailure (executor 8 exited caused by one of the running tasks) Reason: Slave lost
Driver stacktrace:
```

**Comment by anhnongdan** [comment]
A 0 size file is written to disk:
```
191.0 K  573.1 K  /user/hdfs/ds_school/batch02/thangnt/smpl_account_20170910
191.0 K  573.1 K  /user/hdfs/ds_school/batch02/thangnt/smpl_account_h_date
0        0        /user/hdfs/ds_school/batch02/thangnt/smpl_call_histories_20170930
```

**Comment by anhnongdan** [comment]
File format matter when it come to how executor utilize memory.

https://stackoverflow.com/questions/32822948/sparkcontext-was-shut-down-while-running-spark-on-a-large-dataset

**Comment by anhnongdan** [comment]
Reduce the table to just 2887 records and writing still fail.
https://www.evernote.com/shard/s118/nl/12832115/38bb0030-0a15-497e-bf9a-0763e7e59778/

**Comment by anhnongdan** [comment]
If I rerun the code, no active Spark context error occurs.
After SparkContext shutdown, Spark UI is not accessible as well.

```
Py4JJavaError: An error occurred while calling o277.parquet.
: java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
This stopped SparkContext was created at:

org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:59)
sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:423)
py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:234)
py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
py4j.Gateway.invoke(Gateway.java:214)
py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:79)
py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:68)
py4j.GatewayConnection.run(GatewayConnection.java:209)
java.lang.Thread.run(Thread.java:745)

The currently active SparkContext was created at:

(No active SparkContext.)
```

**Comment by anhnongdan** [comment]
Sometime, even count() get the similar error:

```
Py4JJavaError: An error occurred while calling o94.count.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 322 in stage 16.0 failed 4 times, most recent failure: Lost task 322.3 in stage 16.0 (TID 2064, ip-10-58-16-14.dn.pc): ExecutorLostFailure (executor 4 exited caused by one of the running tasks) Reason: Container marked as failed: container_1509082044097_4158_01_000005 on host: ip-10-58-16-14.dn.pc. Exit status: 143. Diagnostics: Container killed on request. Exit code is 143
Container exited with a non-zero exit code 143
Killed by external signal
```

Oh, actually it failed on cache().
-> **So this is consistent with this context**
But notice the input of cache() in the screen shot. 
**Really?? 2.6Gb for just less than 3K records?**


![screen shot 2017-12-26 at 9 47 54 am](https://user-images.githubusercontent.com/9796214/34345497-12570f46-ea22-11e7-9479-d65deb550992.png)

The driver even can't find the IP Address of some executor:
![screen shot 2017-12-26 at 9 53 24 am](https://user-images.githubusercontent.com/9796214/34345581-bc884156-ea22-11e7-9241-20049b016092.png)

**Comment by anhnongdan** [comment]
Reduce the table to as small as few hundred records and caching still fails.
=> I think this is definitely a system problem.'

~~It might due to Resource limit on Spark configuration. But I still don't know why a very small table can cause the whole process to fail.~~

**Comment by anhnongdan** [comment]
But writing account table go really smooth:
![screen shot 2017-12-26 at 10 41 46 am](https://user-images.githubusercontent.com/9796214/34346380-9217d876-ea29-11e7-8004-62a8b7f211ee.png)


![screen shot 2017-12-26 at 10 43 34 am](https://user-images.githubusercontent.com/9796214/34346388-a5f53316-ea29-11e7-89c0-3371a230c76f.png)

**Look at how the cluster works when joining without broadcasting**

![screen shot 2017-12-26 at 11 40 50 am](https://user-images.githubusercontent.com/9796214/34347099-bfee8c60-ea31-11e7-8ca5-efc6da880f05.png)

**Comment by anhnongdan** [comment]
An example on joining dataframe:

```
# To create DataFrame using SQLContext
people = sqlContext.read.parquet("...")
department = sqlContext.read.parquet("...")

people.filter(people.age > 30).join(department, people.deptId == department.id) \
  .groupBy(department.name, "gender").agg({"salary": "avg", "age": "max"})
```

**Comment by anhnongdan** [comment]
collect() gives the same failure:

```
Py4JJavaError: An error occurred while calling o122.collectToPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 326 in stage 17.0 failed 4 times, most recent failure: Lost task 326.3 in stage 17.0 (TID 2416, ip-10-58-16-12.dn.pc): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason: Container marked as failed: container_1509082044097_4183_02_000002 on host: ip-10-58-16-12.dn.pc. Exit status: 143. Diagnostics: Container killed on request. Exit code is 143
Container exited with a non-zero exit code 143
Killed by external signal
```

```
Total Time Across All Tasks: 3.3 min
Locality Level Summary: Node local: 753
Input Size / Records: 3.6 GB / 51404809
Shuffle Write: 1220.7 MB / 19203962
Shuffle Spill (Memory): 3.8 GB
Shuffle Spill (Disk): 1375.3 MB
```

![screen shot 2017-12-26 at 11 05 06 am](https://user-images.githubusercontent.com/9796214/34346681-e8e6cce0-ea2c-11e7-90ce-df7e6f014365.png)

**Comment by anhnongdan** [comment]
Solved by this join:

`history = his_df.join(broadcast(accounts), his_df.sub_encrypted_phone_number == accounts.encrypted_phone_number, 'inner').collect()`

**Just a beginner's mistake**

**Comment by anhnongdan** [comment]
_Reflection: Sometime it's easy to blame the platform. The underlying problem might be difficult to point out just by looking at what happened. Verify every assumptions and conclusions._
