### ISSUE TITLE
Problem Writing (and Reading??) Big parquet file

### ISSUE THREAD

**Issue by anhnongdan** [anhnongdan/Spark1.6_Problems#22]
tc_histories of VT has avg. 300M records.

I got the whole Binh Duong population and join tc_histories to get over 8M records of histories.

Writing parquet with pyspark_small:
```
Py4JJavaError: An error occurred while calling o270.parquet.
: java.lang.ArrayIndexOutOfBoundsException: 8388607
	at com.esotericsoftware.kryo.util.IdentityObjectIntMap.clear(IdentityObjectIntMap.java:345)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.reset(MapReferenceResolver.java:47)
	at com.esotericsoftware.kryo.Kryo.reset(Kryo.java:804)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:570)
```

**No failed job or problem shows on Spark UI**

**Comment by anhnongdan** [comment]
Actually the file was successfully written with 8.2M records

**Comment by anhnongdan** [comment]
`138.0 M  414.1 M  /user/hdfs/ds_school/batch02/thangnt/location_hist_persisted/binh_duong_hist_temp_20170614`

After rereading:

`138.0 M  414.1 M  /user/hdfs/ds_school/batch02/thangnt/location_hist_persisted/binh_duong_hist_temp_20170614`

Check to make sure the file was reread:

```
drwxr-xr-x   - ubuntu hdfs          0 2018-02-22 18:37 /user/hdfs/ds_school/batch02/thangnt/location_hist_persisted/binh_duong_hist_temp_20170613
drwxr-xr-x   - ubuntu hdfs          0 2018-02-22 22:51 /user/hdfs/ds_school/batch02/thangnt/location_hist_persisted/binh_duong_hist_temp_20170614
drwxr-xr-x   - ubuntu hdfs          0 2018-02-22 21:37 /user/hdfs/ds_school/batch02/thangnt/location_hist_persisted/binh_duong_hist_temp_20170615

2018-02-22 22:48:19,073 WARNING [Sampling.LocBasedSampling.continuous_sampling] Read parquet file for 20170614.
2018-02-22 22:51:14,528 WARNING [Sampling.LocBasedSampling.continuous_sampling] Writing file done for 20170614.
```
