### ISSUE TITLE
Out of memory when show table 

### ISSUE THREAD

**Issue by anhnongdan** [anhnongdan/Spark1.6_Problems#7]
The command failed once and then I rerun:
`hist_add.select('concat_phone_number').show(5, False)`

=> I suspect this is due to the df is not un-persisted.

```
Py4JJavaError: An error occurred while calling o260.showString.
: java.lang.OutOfMemoryError: Java heap space
	at org.apache.spark.util.io.ByteArrayChunkOutputStream.allocateNewChunkIfNeeded(ByteArrayChunkOutputStream.scala:66)
	at org.apache.spark.util.io.ByteArrayChunkOutputStream.write(ByteArrayChunkOutputStream.scala:55)
	at org.xerial.snappy.SnappyOutputStream.dumpOutput(SnappyOutputStream.java:343)
	at org.xerial.snappy.SnappyOutputStream.compressInput(SnappyOutputStream.java:357)
	at org.xerial.snappy.SnappyOutputStream.rawWrite(SnappyOutputStream.java:280)
	at org.xerial.snappy.SnappyOutputStream.write(SnappyOutputStream.java:115)
```

**Comment by anhnongdan** [comment]
-> See the memory and disk usage in Executor menu of Spark UI.

![screen shot 2017-12-28 at 10 29 00 am](https://user-images.githubusercontent.com/9796214/34399426-f0e15864-ebb9-11e7-9732-94e56fe5a2ed.png)

=> When 'out of memory' happened, it seems that _all_ executors are dead, all stdout and stderr links are dead???

**Comment by anhnongdan** [comment]
Java heap is hosted on driver. 
I might need a bigger dirver for this task.

https://stackoverflow.com/questions/32336915/pyspark-java-lang-outofmemoryerror-java-heap-space

https://stackoverflow.com/questions/21138751/spark-java-lang-outofmemoryerror-java-heap-space

**Comment by anhnongdan** [comment]
***Tried unpersist the DFs but still fail. It seems the heap is not freed right away.***
Restart kernel...

**Oh, after restarting kernel. The code runs much smoother with df unpersist...**

**Comment by anhnongdan** [comment]
Actually, show() trigger the calculations on dfs. 
If I forget to unpersist other df and executor's memory is loaded, it's normal to get the Memory overhead error.
